# Nova-MCP Server Configuration Example
# Copy this file to config.toml and customize as needed

[server]
port = 8080
log_level = "info"
transport = "stdio"  # Options: "stdio", "sse", "http"

[apis]
# Optional API keys for enhanced functionality
# uniswap_api_key = "your_uniswap_api_key_here"
# coingecko_api_key = "your_coingecko_api_key_here"
# dexscreener_api_key = "your_dexscreener_api_key_here"
rate_limit_per_minute = 60

[cache]
ttl_seconds = 300      # Cache time-to-live in seconds
max_entries = 1000     # Maximum number of cached entries

[auth]
# Enable API key authentication for HTTP transport
enabled = false
# Comma-separated list of allowed API keys (development only; replace with a secure store in production)
allowed_keys = []
# Header name to read API key from
header_name = "x-api-key"
