services:
  nova-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nova-mcp-server
    environment:
      - NOVA_MCP_LOG_LEVEL=info
      - NOVA_MCP_TRANSPORT=http
      - NOVA_MCP_PORT=8080
      # Add API keys as needed
      # - UNISWAP_API_KEY=${UNISWAP_API_KEY}
      # - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      # - DEXSCREENER_API_KEY=${DEXSCREENER_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      # Persist the Sled database for user/group plugin configurations
      - ./data:/app/nova_mcp_db
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      # Check that the HTTP endpoint responds (no bash/grep required)
      test: ["CMD", "sh", "-c", "curl -fsS -m 5 -X POST http://localhost:8080/rpc -H 'Content-Type: application/json' -d '{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":1,\\\"method\\\":\\\"tools/list\\\"}' > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
